### ISSUE TITLE
Enable es6.constants

### ISSUE THREAD

**Issue by stubailo** [meteor/babel#1]

**Comment by stubailo** [comment]
This is pretty crucial to catch errors where you accidentally assign to constants. It also enables the workflow of replacing all vars to constants, and then figuring out what to do about the ones that are actually assigned to.

**Comment by dgreensp** [comment]
Actually, without this transformer, `const` is not transpiled into `var` at all, it just stays `const`.

**Comment by dgreensp** [comment]
Interestingly, most browsers have supported `const` for a while (but not with strict semantics until recently).  But we need this transformer for IE10 and below.

**Comment by stubailo** [comment]
Actually, I think es6.blockscoping transforms const into var?

**Comment by stubailo** [comment]
I could be totally wrong though, their documentation is terrible on this

**Comment by dgreensp** [comment]
The headings on that page aren't one-to-one with the transformers, confusingly.

I think most people just run Babel with the default settings so they don't run into this.

I tried transpiling with and without `es6.constants`.

**Comment by stubailo** [comment]
Ah, OK then we definitely need to transpile it. Confusingly, my code seemed to run in Node.js without this transform, even though I was using `const`.

**Comment by dgreensp** [comment]
Yeah, `const` works in Node.
