### ISSUE TITLE
Enable 'es3.propertyLiterals'

### ISSUE THREAD

**Issue by stubailo** [meteor/babel#2]

**Comment by benjamn** [comment]
This transform actually didn't work when I tested it. That is,

``` js
function getFoo(x) {
  return x["foo"];
}
```

was not transformed to

``` js
function getFoo(x) {
  return x.foo;
}
```

**Comment by benjamn** [comment]
And I wasn't motivated enough to debug it. This seems like the job of a minifier, unless it has some other value besides saving bytes.

**Comment by stubailo** [comment]
https://babeljs.io/docs/advanced/transformers/es3/property-literals/

I don't think that's what this is supposed to do. It just converts keywords to quoted strings.

**Comment by stubailo** [comment]
I'm a little confused at this point because the "in" and "out" examples don't seem to be consistent with "minification" which is in the name?

**Comment by dgreensp** [comment]
"minification" was in the old name.  They just forgot to update the usage.

This is basically so that you can use keywords in object literals and not worry about IE 8 compat.

**Comment by benjamn** [comment]
Ah, so `es3.propertyLiterals` is for object literal keys like `{ catch: 1 }`, whereas `es3.memberExpressionLiterals` is for things like `x.catch`.

**Comment by dgreensp** [comment]
Yeah, exactly!
