### ISSUE TITLE
The version of meteor-babel should be 7.9.0

### ISSUE THREAD

**Issue by afrokick** [meteor/babel#32]
After release 1.10.2 the meteor-babel's version should be 7.9.0. https://github.com/meteor/meteor/commit/156bdcd705b1abd31ffa3ff8edb565532ce12127

On npm the version also 7.9.0 https://www.npmjs.com/package/meteor-babel

Seems like @benjamn forgot to commit changes in this repo)

**Comment by afrokick** [comment]
@filipenevola FYI

**Comment by filipenevola** [comment]
Thanks @afrokick, I am going to check.

**Comment by filipenevola** [comment]
Good catch @afrokick, it's fixed now https://github.com/meteor/babel/commit/052a584a493c57febd585d204990be6cc953779d
