### ISSUE TITLE
Not running on client?

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/babel#6]
I used to use grigio:babel which is now marked as "deprecated" because of the new babel-compiler package. But I have troubles using this, as babel-compiler does not support client code. Why is this so? I should be no problem to transpile it for the client during the build process, as it is possible with grunt / gulp for quite a long time. Supporting babel on the server only is a huge drawback.

**Comment by benjamn** [comment]
Compilation happens on the server, whether you're compiler server code or client code. Meteor supports ECMAScript 2015 on both client and server. Just run `meteor add ecmascript`!
